#!/usr/bin/env node
import { createHash } from 'crypto';
import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { ROOT } from './lib/medcheck-source-loader.js';
import { writeJson } from './lib/enrichment-common.js';

const DEFAULT_CACHE_DIR = resolve(ROOT, 'data/enrichment/cache/cpic');
const DEFAULT_RAW_DIR = resolve(ROOT, 'data/enrichment/snapshots/cpic-raw');
const CPIC_BASE = 'https://api.cpicpgx.org/v1';

function parseArgs(argv) {
  const args = { cacheDir: DEFAULT_CACHE_DIR, rawDir: DEFAULT_RAW_DIR, limit: 50 };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--cache-dir') args.cacheDir = resolve(ROOT, argv[++i]);
    else if (arg.startsWith('--cache-dir=')) args.cacheDir = resolve(ROOT, arg.slice(12));
    else if (arg === '--raw-dir') args.rawDir = resolve(ROOT, argv[++i]);
    else if (arg.startsWith('--raw-dir=')) args.rawDir = resolve(ROOT, arg.slice(10));
    else if (arg === '--limit') args.limit = Number(argv[++i]);
    else if (arg.startsWith('--limit=')) args.limit = Number(arg.slice(8));
  }
  return args;
}

const ENDPOINTS = [
  'gene',
  'drug',
  'pair_view',
  'guideline',
  'recommendation_view',
  'publication',
  'test_alert_view',
  'allele_definition',
];

const args = parseArgs(process.argv.slice(2));
mkdirSync(args.cacheDir, { recursive: true });
mkdirSync(args.rawDir, { recursive: true });

const fetched = [];
const providerFailures = [];

for (const endpoint of ENDPOINTS) {
  const params = { limit: Number.isFinite(args.limit) ? args.limit : 50 };
  const url = `${CPIC_BASE}/${endpoint}?limit=${params.limit}`;
  try {
    const res = await fetch(url, { headers: { accept: 'application/json' } });
    const text = await res.text();
    const sha256 = createHash('sha256').update(text).digest('hex');
    let response = null;
    try {
      response = JSON.parse(text);
    } catch {
      response = { rawText: text.slice(0, 500) };
    }
    const payload = {
      source: 'CPIC Data',
      fetchedAt: new Date().toISOString(),
      url,
      endpoint,
      params,
      status: res.status,
      etag: res.headers.get('etag') || '',
      lastModified: res.headers.get('last-modified') || '',
      sha256,
      response,
    };
    const file = resolve(args.cacheDir, `${endpoint}-${sha256.slice(0, 12)}.json`);
    writeJson(file, payload);
    fetched.push({ endpoint, file, status: res.status, sha256, records: Array.isArray(response) ? response.length : 0 });
    if (!res.ok) providerFailures.push({ endpoint, status: res.status, url });
  } catch (error) {
    providerFailures.push({ endpoint, status: 'network_error', error: error.message, url });
  }
}

const index = {
  schema: 'diognosis.cpic-raw-cache-index.v1',
  generatedAt: new Date().toISOString(),
  source: 'CPIC Data',
  baseUrl: CPIC_BASE,
  fetched,
  providerFailures,
};

writeJson(resolve(args.rawDir, 'index.json'), index);
writeFileSync(resolve(args.rawDir, 'README.md'), '# CPIC Raw Cache\n\nGenerated by `scripts/enrich/cpic-fetch.js`. Raw responses are script-time cache artifacts and are not trusted clinical content.\n');
console.log(JSON.stringify({ ok: providerFailures.length === 0, fetched: fetched.length, providerFailures, index: resolve(args.rawDir, 'index.json') }, null, 2));
if (providerFailures.length) process.exitCode = 2;
