#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import { collectStats } from './collect-stats.js';

const root = resolve(new URL('..', import.meta.url).pathname);
const stats = collectStats();
const bundlePath = resolve(root, 'index.html');

if (existsSync(bundlePath)) {
  const html = readFileSync(bundlePath, 'utf8');
  stats.bundleBytes = Buffer.byteLength(html, 'utf8');
  stats.bundleKB = Math.round(stats.bundleBytes / 1024);
  stats.bundleLines = html.split('\n').length;
}

const generatedSource = `// Auto-generated by scripts/gen-stats.js. Do not edit by hand.
const MEDCHECK_STATS = ${JSON.stringify(stats, null, 2)};
`;
writeFileSync(resolve(root, 'src/data/generatedStats.js'), generatedSource, 'utf8');

const readmePath = resolve(root, 'README.md');
const readme = readFileSync(readmePath, 'utf8');
const start = '<!-- MEDCHECK_STATS_START -->';
const end = '<!-- MEDCHECK_STATS_END -->';
const candidateSuffix = (pending, expanded) =>
  pending ? ` (+${pending} pending candidates; ${expanded} candidate-expanded)` : '';
const typedCandidateLine = stats.pendingCoreTotalCandidates
  ? `- **${stats.pendingCoreTotalCandidates} typed pending core candidates** derived from source-linked enrichment (non-scoring, pending verification)
`
  : '';
const statsBlock = `${start}
- **${stats.drugs} drugs** in DRUG_DB${candidateSuffix(stats.pendingCoreDrugCandidates || 0, stats.candidateExpandedDrugs || stats.drugs)}
- **${stats.studies} evidence entries** in STUDY_DB (${stats.studiesWithPmid} with PMIDs; ${stats.sourceLinkedStudies} with source identifiers) — **${stats.pendingProfessionalReviewStudies} not professionally reviewed**, **${stats.professionalReviewedStudies} professionally reviewed**${candidateSuffix(stats.pendingCoreStudyCandidates || 0, stats.candidateExpandedStudies || stats.studies)}
- **${stats.pendingReviewEnrichmentRecords || 0} pending-review enrichment records** from **${stats.pendingReviewEnrichmentSources || 0} external source groups** (context only; non-scoring)
${typedCandidateLine}- **${stats.ddiPairs} interaction pairs** (${stats.severeDdi} severe, ${stats.moderateDdi} moderate, ${stats.mildDdi} mild)${candidateSuffix(stats.pendingCoreInteractionCandidates || 0, stats.candidateExpandedDdiPairs || stats.ddiPairs)}
- **${stats.metaboliteEntries} metabolite entries** across **${stats.metaboliteParents} parent substances** (${stats.metaboliteActors} first-class metabolite actors)${candidateSuffix(stats.pendingCoreMetaboliteCandidates || 0, stats.candidateExpandedMetaboliteEntries || stats.metaboliteEntries)}
- **${stats.pkParams} absolute PK simulation profiles** with relative fallback for half-life-only drugs${candidateSuffix(stats.pendingCorePkCandidates || 0, stats.candidateExpandedPkProfiles || stats.pkParams)}
- **${stats.genotypeGenes} genotype genes** and **${stats.receptorScores} receptor score profiles** (+${stats.pendingCorePgxCandidates || 0} pending PGx rule candidates across ${stats.pendingCoreUniquePgxGenes || 0} genes; ${stats.candidateExpandedGenotypeGenes || stats.genotypeGenes} candidate-expanded genes, ${stats.candidateExpandedReceptorProfiles || stats.receptorScores} candidate-expanded receptor/phenotype profiles)
- **${stats.beersFlags} Beers flags** and **${stats.washoutRules} washout rules** (+${stats.pendingCoreBeersCandidates || 0} Beers candidates; +${stats.pendingCoreWashoutCandidates || 0} washout candidates; ${stats.candidateExpandedBeersFlags || stats.beersFlags}/${stats.candidateExpandedWashoutRules || stats.washoutRules} candidate-expanded)
- **${stats.bundleKB || 'Not yet built'} KB** generated bundle${stats.bundleLines ? ` (${stats.bundleLines} lines)` : ''}
${end}`;

let nextReadme;
if (readme.includes(start) && readme.includes(end)) {
  nextReadme = readme.replace(new RegExp(`${start}[\\s\\S]*?${end}`), statsBlock);
} else {
  nextReadme = readme.replace(
    '---\n\n## Features',
    `---\n\n## Live Source Stats\n\n${statsBlock}\n\n---\n\n## Features`
  );
}
writeFileSync(readmePath, nextReadme, 'utf8');

process.stdout.write(`Generated stats: ${stats.drugs} drugs, ${stats.studies} studies, ${stats.ddiPairs} DDI pairs\n`);
